export const ADD_NEW_CATEGORY_BUTTON = "ADD_NEW_CATEGORY_BUTTON";
export const ADD_MODAL_CATEGORY = "ADD_MODAL_CATEGORY";
export const ADD_NEW_CATEGORY = "ADD_NEW_CATEGORY";
export const MOCKUP_IMGS_FETCH = "MOCKUP_IMGS_FETCH";
export const MOCK_STORE_IMGS = "MOCK_STORE_IMGS";

export const DISPATCH_MONTH_CHANGE = "DISPATCH_MONTH_CHANGE";
export const DISPATCH_YEAR_CHANGE = "DISPATCH_YEAR_CHANGE";
